replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  tag: latest
  pullPolicy: Always

kafka:
  brokerConnect: kafka.elastic.svc.cluster.local:9092
  properties: ""
  truststore: ""
  keystore: ""
  propertiesFile: "kafka.properties"
  truststoreFile: "kafka.truststore.jks"
  keystoreFile: "kafka.keystore.jks"

host:

jvm:
  opts: "-Xms32M -Xmx64M"
jmx:
  port: 8686

nameOverride: ""
fullnameOverride: ""

cmdArgs: ""

server:
  port: 9000
  servlet:
    contextPath: /

service:
  annotations: {}
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: []
  tls: []

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
    cpu: 1m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

mountProtoDesc: 
  enabled: false
  hostPath: